function on_message(self, message_id, message, sender)
	if message_id == hash("enable-my_house_sign") then
		gui.set_visible(gui.get_node("box"), true)
		gui.set_visible(gui.get_node("text"), true)
		msg.post("/logic#village_logic", "my_house_sign-enabled")
	elseif message_id == hash("disable-my_house_sign") then
		gui.set_visible(gui.get_node("box"), false)
		gui.set_visible(gui.get_node("text"), false)
	end
end
